
host: "127.0.0.1"
port: 12371
certfile: "./cert.pem"
attack: NA    #attack为攻击方式label flipping attack:LFA  //model poisoning attacks:MPA   //no attack:NA
path_to_save: ./checkpoints
key_distribution_server_ip: "127.0.0.1"
key_distribution_server_port: 6653
key_distribution_server_certfile: "./cert.pem"