host: "127.0.0.1"  # 服务器的IP地址
port: 12371       # 服务器监听的端口号
key_distribution_server_ip: "127.0.0.1"
key_distribution_server_port: 6653
port_used_for_fetching_context: 22224
certfile: "cert.pem"  # SSL证书文件的路径
keyfile: "key.pem"   # SSL私钥文件的路径
is_cpu: true         # 是否使用CPU
gpu: "0"            # 使用的GPU ID
num_of_clients: 1   # 客户端的数量
cfraction: 1.0      # 随机挑选的客户端的比例
epoch: 1            # 客户端本地训练的迭代次数
batchsize: 16       # 客户端本地训练的批次大小
model_name: "cifar10_cnn"  # 训练模型的名称
learning_rate: 0.0002     # 学习率
dataset: "cifar10"        # 使用的数据集
save_freq: 100            # 全局模型保存的频率（通信次数）
num_communication_rounds: 100             # 通信次数（训练轮次）
saved_model_parameters: ""  # 加载的模型参数路径,如果为空则不加载
IID: 1                    # 数据分配方式（IID数据分布）
algorithm: "APFL"         # 使用的联邦学习算法
pr: 0.0                   # 污染数据的比例
